spring:
  application:
    name: insurance-policies
  datasource:
    url: jdbc:h2:mem:insurance-policies
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 4040
  servlet:
    context-path: /api

resources:
  policies: /policies/